name: Build, Test, and Push to Codecov

on:
  push:
    branches: [ "main" ]

jobs:
  build_test_and_push_to_codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Fetch main branch
        run: |
          git remote set-branches --add origin main
          git fetch origin main

      # Install Flutter
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git $HOME/flutter -b stable
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$PATH:$HOME/flutter/bin"
          export PATH="$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter precache
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      # Run tests with coverage
      - name: Run tests
        run: flutter test --coverage

      - name: Generate coverage report
        run: |
          sudo apt-get install lcov
          lcov --list ./coverage/lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ChopinDavid/grammatika
