name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build_and_upload_to_google_play:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git $HOME/flutter -b stable
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "$HOME/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
          export PATH="$PATH:$HOME/flutter/bin"
          export PATH="$HOME/flutter/bin/cache/dart-sdk/bin:$PATH"
          flutter precache
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.PACKAGE_NAME }}
          releaseFile: build/app/outputs/bundle/release/app-release.aab
          track: internal